name: Render documents with rmarkdown-action
on: [push]
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-rmd@v1
        with:
          input_file: R/intro-to-r.Rmd
	  output_format: html_document
